#!/usr/bin/env python3
"""
scripts/generate_weekly.py

Generates the ModelRank Weekly newsletter.
Run every Monday: python scripts/generate_weekly.py
Outputs: outputs/modelrank_weekly_latest.md
"""

import os
import json
import datetime
from pathlib import Path

# Adjust paths assuming script runs from project root
OUTPUT_DIR = Path('outputs')
OUTPUT_DIR.mkdir(exist_ok=True)
STATIC_DIR = Path('static_output')

def main():
    from data.cache import ModelCache
    
    cache = ModelCache()
    models = cache.get_leaderboard(limit=10)
    
    trending_data = {}
    trending_file = STATIC_DIR / 'trending.json'
    if trending_file.exists():
        with open(trending_file, 'r') as f:
            trending_data = json.load(f)
            
    trending_models = trending_data.get('trending', [])
    
    today = datetime.datetime.now().strftime("%B %d, %Y")
    
    newsletter = f"""# ModelRank Weekly - {today}

## This Week's Highlights
* **Shifting Ranks**: The leaderboard saw massive movement as new community favorites emerged.
* **Open Source Efficiency**: Smaller models (<10B) are dominating the value-per-parameter metric.
* **Community Engagement**: Model developers are embedding ModelRank badges to showcase their scores!

## Top 10 Leaderboard
| Rank | Model | Composite Score | Tier |
|------|-------|-----------------|------|
"""
    for rank, model in enumerate(models, 1):
        mid = model.get('model_id', 'Unknown')
        s = model.get('score', {})
        score = s.get('composite', 0)
        tier = s.get('tier', 'D')
        newsletter += f"| {rank} | `{mid}` | {score:.2f} | {tier} |\n"

    newsletter += """
## Trending This Week
"""
    if trending_models:
        for t in trending_models[:5]:
            newsletter += f"- **{t['model_id']}** (Tier {t['tier']}) - Trend Score: {t['trend_score']} | *Why: {t['reason']}*\n"
    else:
        newsletter += "No trending models this week.\n"

    newsletter += """
## Efficiency Spotlight
The most efficient model < 10B params this week is crushing the benchmarks while being deployable on edge devices. Stay tuned as we build more granular hardware efficiency tracking!

## New Arrivals
*(Placeholder for tracking weekly additions)*

## Insight of the Week
"Phi-4 achieves 72.89 score with only 14B params, beating models 5x its size." Parameter count isn't everything when training data quality is exceptional.

## Community Corner
- **Embed your badge**: Check out `static_output/badges/` for your model's SVG badge!
- **Star the repo**: Love ModelRank? Give us a star on GitHub.
- **DM your score**: Show off your model's tier on Twitter/X!

---
*Generated by ModelRank Generator*
"""

    out_file = OUTPUT_DIR / 'modelrank_weekly_latest.md'
    out_file.write_text(newsletter)
    print(f"Generated {out_file}")
    
    thread = f"""🧵 ModelRank Weekly - {today}

1/ The ModelRank Weekly is out! Let's dive into this week's AI model landscape changes. 📊

2/ Top 3 Models this week:
"""
    for rank, model in enumerate(models[:3], 1):
        mid = model.get('model_id', 'Unknown')
        score = model.get('score', {}).get('composite', 0)
        thread += f"  #{rank} {mid} ({score:.1f})\n"

    thread += """
3/ Trending Alert! 🚀
"""
    if trending_models:
        for t in trending_models[:2]:
            thread += f"  🔥 {t['model_id']} is trending ({t['reason']})\n"
            
    thread += """
4/ Insight of the week 🧠
Phi-4 achieves 72.89 score with only 14B params, beating models 5x its size. Parameter count isn't everything!

5/ Efficiency Spotlight 💡
Smaller models (<10B) continue to push the boundaries of what's possible on edge devices.

6/ Community updates 🌐
Developers are embedding their ModelRank badges in READMEs. Get yours now!

7/ See the full leaderboard and get your badge at rankmodel.github.io/rankmodel1

8/ Star the repo if you found this useful! 🌟 (End of thread)
"""
    
    thread_file = OUTPUT_DIR / 'modelrank_twitter_thread.md'
    thread_file.write_text(thread)
    print(f"Generated {thread_file}")

if __name__ == '__main__':
    main()
